DROP TABLE IF EXISTS Produto;
create table Produto (id integer generated by default as identity, dataLancamento timestamp, descricao varchar(255),sumarioPath varchar(255), paginas integer not null, titulo varchar(255), primary key (id));
DROP TABLE IF EXISTS Produto_precos;
create table Produto_precos (Produto_id integer not null, tipo integer, valor decimal(19,2));
alter table Produto_precos add constraint FK_produto_produto_preco foreign key (Produto_id) references Produto;